title: "이영규"
description: "꿈을 위해 열심히 노력하는 이영규입니다."
site_title: "축제를 사랑하는 사람"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: YoungGyu99
email: robot090831@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/myimg.jpg
