description: "사람들의 여행에 대한 꿈을 현실화 시켜주고 싶은 개발자준비생입니다."
site_title: "여행을사랑하는 개발자"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: YoungGyu99
email: robot090831@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/myimg.jpg

title: "            <center>이영규</center>"

